feat: 更改打包

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,7 +19,7 @@ jobs:
           java-version: '17'  # 根据项目需要选择 Java 版本
 
       - name: Build with Maven
-        run: mvn clean install
+        run: mvn clean package spring-boot:repackage
 
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.3
@@ -38,7 +38,13 @@ jobs:
           ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p $TEMP_PATH"
 
           # 获取所有生成的 JAR 文件
-          JAR_FILES=$(find . -name "*.jar" -not -path "*/target/original-*.jar")
+          JAR_FILES=$(find target -name "*.jar" -not -path "*/target/original-*.jar")
+
+          # 检查 JAR 文件是否存在
+          if [ -z "$JAR_FILES" ]; then
+            echo "Error: No JAR files found"
+            exit 1
+          fi
 
           # 将构建的 JAR 文件传输到临时目录
           for jar in $JAR_FILES; do
@@ -46,17 +52,19 @@ jobs:
           done
 
           # 连接到服务器并执行部署脚本
-          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
+          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
             # 停止当前服务
             sudo systemctl stop $SERVICE_NAME
           
             # 删除旧服务文件
             sudo rm -rf $DEPLOY_PATH/*.jar
 
-            # 移动 JAR 文件到目标目录并重命名
+            # 移动 JAR 文件到目标目录
             sudo mv $TEMP_PATH/*.jar $DEPLOY_PATH/
 
             # 启动服务
             sudo systemctl start $SERVICE_NAME
 
+            # 清理临时目录
+            rm -rf $TEMP_PATH
           EOF
